[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Jon Kerry <jonathan.kerry@congenica.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
regex = "1.4.3"
trees = "0.3.0"